### ISSUE TITLE
http URLs are problematic except when used in subdomains

### ISSUE THREAD

**Issue by quimgil** [miraheze/dns#1]
While https://miraheze.org and https://spiral.wiki show correctly the site, http://miraheze.org and http://spiral.wiki leads to Apache2 Debian Default Page

http://spiral.wiki/wiki/Contribute results in Not Found, however http://meta.miraheze.org/wiki/ redirects to https just fine.

Tested with Firefox and Chrome in a laptop booted today for the first time in a month (so no cache problems).

**Comment by quimgil** [comment]
This might be something weird with... some cache somewhere. 

Update:

* Now the spiral.wiki URLs above work.
* Clicking http://miraheze.org/ here: Apache2 Debian Default Page
* Clicking  http://meta.miraheze.org/wiki/ 404 Not Found nginx/1.6.2

**Comment by quimgil** [comment]
Maybe related?

https://wikiapiary.com/wiki/Spiral shows links Not Found to http://spiral.wiki/w/api.php?action=query&meta=siteinfo&siprop=statistics&format=json which, indeed, bring Not Found in my browser.

However, https://spiral.wiki/w/api.php?action=query&meta=siteinfo&siprop=statistics&format=json does work in my browser.

**Comment by Southparkfan** [comment]
Hi, both http://spiral.wiki and http://meta.miraheze.org give me this:
* Connected to spiral.wiki (185.52.1.75) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: spiral.wiki
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
* Server nginx/1.6.2 is not blacklisted
< Server: nginx/1.6.2
< Date: Tue, 04 Aug 2015 10:33:33 GMT
< Content-Type: text/html
< Content-Length: 184
< Location: http://spiral.wiki/wiki/
< Connection: keep-alive
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>

Visiting the MediaWiki API over http:// works normal too.

**Comment by quimgil** [comment]
Works now from different desktop and mobile browsers. I was having problems with some combinations still this morning. Closing.
