### ISSUE TITLE
Geographically load balance and failover DNS requests

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/dns#2]
All requests should be geogrpahically load balanced between cp1 and cp2 and then a fail over suggestion put in place about whether we fail to the other cp1 and then mw or straight to mw.

**Comment by JohnFLewis** [comment]
Considering this and to avoid complexity for now:

North America: cp2 -> cp1 -> mw1
South America: cp2 -> cp1 -> mw1
Europe: cp1 -> mw1
Asia: needs more consideration and in depth likely per country. latency to cp2 is less and greater than cp1
Oceania: cp2 -> cp1 -> mw1

Default will be: cp1 -> mw1 (for all countries missed)

**Comment by Southparkfan** [comment]
Seems sane to me. Pending comments about Asia.

We're not big enough for a multi-DC setup (and even the WMF doesn't use that in production yet), but that would be cool for the future.

**Comment by JohnFLewis** [comment]
A list of countries I will route to cp2 from Asia are below. I'll not list all countries out and let them be caught by the default string.

BT
BD
MM
LA
TH
KH
VN
MY
SG
PH
CN
KP
KR
JP
ID

**Comment by JohnFLewis** [comment]
johnflewis@bastion:~$ ssh ns1.miraheze.org "host miraheze.org"
miraheze.org has address 107.191.126.23
miraheze.org has IPv6 address 2604:180:0:33b::2

johnflewis@bastion:~$ ssh ns2.miraheze.org "host miraheze.org"
miraheze.org has address 81.4.124.61
miraheze.org has IPv6 address 2a00:d880:5:569::2

johnflewis@bastion:~$ ssh ns3.miraheze.org "host miraheze.org"
miraheze.org has address 107.191.126.23
miraheze.org has IPv6 address 2604:180:0:33b::2

johnflewis@bastion:~$ host miraheze.org
miraheze.org has address 81.4.124.61
miraheze.org has IPv6 address 2a00:d880:5:569::2
